configuration:
  is-obfuscation-enabled: false
  sensitive-regular-expressions:
    - id: 1
      name: 'Social Security Number'
      pattern: '\b(?:[1-6][0-4]\d|0[1-4]\d|00[1-9])-(?:0[1-9]|[1-9]\d)-(?:000[1-9]|00[1-9]\d|0[1-9]\d{2}|[1-9]\d{3})\b'
      importance: 1

    - id: 2
      name: 'Password Number'
      pattern: '\b(?:[A-Za-z]{2}\d{7}|\d{9})\b'
      importance: 1

    - id: 3
      name: 'ICCID'
      pattern: '\b89\d{17,18}\b'
      importance: 1

  field-names: ['message']
  white-regular-expressions: []
  stream-titles: ['Audit logs']
  text-replacer: 'Static Star Replacer'

